name: ambic-epigenome
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.6
  - snakemake=5.7.1
  - minimap2=2.17
  - samtools=1.9
  - sniffles=1.0.11
  - survivor=1.0.6
  - bcftools=1.9
  - nanopolish=0.11.2
  - pysam=0.15.3
