workdir: /kyber/Data/NGS/projects/ambic/combined # path to save the analysis outputs
codedir: /home/isac/Code/projects/ambic-epigenome # path to this dir
#reference: /mnt/c/ref/Cricetulus_griseus_chok1gshd.sigmaIgG.fa # path to reference genome
reference: /mithril/Data/NGS/Reference/cho/chok1/genome/Cricetulus_griseus_chok1gshd.nihIgG.fa
threads: 10 # available cores
