workdir: /mnt/c # path to save the analysis outputs
codedir: /home/ubuntu/Code/ambic-epigenome # path to this dir
reference: /mnt/c/ref/Cricetulus_griseus_chok1gshd.sigmaIgG.fa # path to reference genome
threads: 72 # available cores
